version: "3.4"

services: 
    backendapi:
        build:
            context: .
            dockerfile: contoso-api/Dockerfile
        container_name: contoso-api
        ports: 
            - 5000:80
        
    frontend:
        build:
            context: ./contoso-app
            dockerfile: Dockerfile
        container_name: contoso-app
        ports:
            - 5050:80
        depends_on: 
            - backendapi